#! /usr/bin/env sh

if [[ $(cat ~/dmenu\ scripts/themes/.current) == 1 ]]; then
    export appliedwall=$(tail -n 1 ~/dmenu\ scripts/themes/Xmonad)
    $appliedwall
fi

if [[ $(cat ~/dmenu\ scripts/themes/.current) == 2 ]]; then
    export appliedwall=$(tail -n 1 ~/dmenu\ scripts/themes/Qtile)
    $appliedwall
fi

if [[ $(cat ~/dmenu\ scripts/themes/.current) == 3 ]]; then
    export appliedwall=$(tail -n 1 ~/dmenu\ scripts/themes/qtile_reddit_rice)
    $appliedwall
fi

if [[ $(cat ~/dmenu\ scripts/themes/.current) == 4 ]]; then
    export appliedwall=$(tail -n 1 ~/dmenu\ scripts/themes/Palenight)
    $appliedwall
fi
