#! /usr/bin/env sh

# remove current sketchybar config
rm -r ~/.config/sketchybar

rm -r ~/.config/nvim/
cp -r /Users/itaysharir/dmenu\ scripts/themes/.nvim-palenight ~/.config/nvim

# move desired sketchybar config to the correct location
cp -r ~/dmenu\ scripts/themes/.yabai_panelight/yabairc ~/.config/yabai/yabairc

# restart sketchybar to apply new config
brew services stop sketchybar

# restart yabai
brew services restart yabai

rm -r ~/.config/alacritty/
cp -r ~/dmenu\ scripts/themes/.alacritty-palenight ~/.config/alacritty/

echo 4 > /Users/itaysharir/dmenu\ scripts/themes/.current

wal -i /Users/itaysharir/wallpapers/new/wallpaper.jpg
