#! /usr/bin/env sh

brew services start sketchybar

# remove current sketchybar config
rm -r ~/.config/sketchybar

rm -r ~/.config/nvim/
cp -r /Users/itaysharir/dmenu\ scripts/themes/.nvim-else ~/.config/nvim

# move desired sketchybar config to the correct location
cp -r ~/dmenu\ scripts/themes/.sketchybar-qtile ~/.config/sketchybar
cp -r ~/dmenu\ scripts/themes/.yabai_qtile-xmonad/yabairc ~/.config/yabai/yabairc

brew services restart sketchybar
brew services restart yabai

rm -r ~/.config/alacritty/
cp -r ~/dmenu\ scripts/themes/.alacritty-else ~/.config/alacritty/

echo 2 > /Users/itaysharir/dmenu\ scripts/themes/.current

wal -i /Users/itaysharir/wallpapers/dt/0139.jpg
