#! /usr/bin/env sh

# remove current sketchybar config
rm -r ~/.config/sketchybar

rm -r ~/.config/nvim/
cp -r /Users/itaysharir/dmenu\ scripts/themes/.nvim-else ~/.config/nvim

# move desired sketchybar config to the correct location
cp -r ~/dmenu\ scripts/themes/.sketchybar-xmonad ~/.config/sketchybar
cp -r ~/dmenu\ scripts/themes/.yabai_qtile-xmonad/yabairc ~/.config/yabai/yabairc

# restart sketchybar to apply new config
brew services restart sketchybar

# restart yabai
brew services restart yabai

rm -r ~/.config/alacritty/
cp  -r ~/dmenu\ scripts/themes/.alacritty-else ~/.config/alacritty/

echo 1 > /Users/itaysharir/dmenu\ scripts/themes/.current

wal -i /Users/itaysharir/wallpapers/dt/0005.jpg
