#! /usr/bin/env sh

# remove current sketchybar config
rm -r ~/.config/sketchybar

# move desired sketchybar config to the correct location
cp -r ~/dmenu\ scripts/themes/.sketchybar-qtile ~/.config/sketchybar
cp -r ~/dmenu\ scripts/themes/.yabai_qtile-xmonad/yabairc ~/.config/yabai/yabairc

brew services restart sketchybar
brew services restart yabai

echo 2 > /Users/itaysharir/dmenu\ scripts/themes/.current

wal -i /Users/itaysharir/wallpapers/dt/0139.jpg
